version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/kb_files:/app/backend/kb_files
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000
